AllCops:
  Exclude:
    - 'test/**/*.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 3.2.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/MultilineBlockChain:
  Enabled: false

Layout/LineLength:
  Max: 120
