# frozen_string_literal: true

module Trello2Notion
  module Notion
    LANGUAGE = {
      abap: "abap",
      arduino: "arduino",
      bash: "bash",
      basic: "basic",
      c: "c",
      clojure: "clojure",
      coffeescript: "coffeescript",
      cpp: "c++",
      csharp: "c#",
      css: "css",
      dart: "dart",
      diff: "diff",
      docker: "docker",
      elixir: "elixir",
      elm: "elm",
      erlang: "erlang",
      flow: "flow",
      fortran: "fortran",
      fsharp: "f#",
      gherkin: "gherkin",
      glsl: "glsl",
      go: "go",
      graphql: "graphql",
      groovy: "groovy",
      haskell: "haskell",
      html: "html",
      java: "java",
      javascript: "javascript",
      json: "json",
      julia: "julia",
      kotlin: "kotlin",
      latex: "latex",
      less: "less",
      lisp: "lisp",
      livescript: "livescript",
      lua: "lua",
      makefile: "makefile",
      markdown: "markdown",
      markup: "markup",
      matlab: "matlab",
      mermaid: "mermaid",
      nix: "nix",
      objective_c: "objective-c",
      ocaml: "ocaml",
      pascal: "pascal",
      perl: "perl",
      php: "php",
      plain_text: "plain text",
      powershell: "powershell",
      prolog: "prolog",
      protobuf: "protobuf",
      python: "python",
      r: "r",
      reason: "reason",
      ruby: "ruby",
      rust: "rust",
      sass: "sass",
      scala: "scala",
      scheme: "scheme",
      scss: "scss",
      shell: "shell",
      sql: "sql",
      swift: "swift",
      typescript: "typescript",
      vb_net: "vb.net",
      verilog: "verilog",
      vhdl: "vhdl",
      visual_basic: "visual basic",
      webassembly: "webassembly",
      xml: "xml",
      yaml: "yaml",
      java_c_cpp_cs: "java/c/c++/c#"
    }.freeze
  end
end
